global:
  scrape_interval: 15s  # Global scrape interval
  evaluation_interval: 1m  # Expression evaluation interval

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  # Scrape interval for Prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Targeting node_exporter

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']